name: CI Pipeline


on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ruff-lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          pip install ruff
          ruff check .

  pytest:
    runs-on: ubuntu-latest
    needs: ruff-lint

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB_AUTH: ${{ secrets.POSTGRES_DB_AUTH }}
      POSTGRES_DB_UNIVERSITY: ${{ secrets.POSTGRES_DB_UNIVERSITY }}
      AUTH_SERVICE_INTERNAL_URL: ${{ secrets.AUTH_SERVICE_INTERNAL_URL }}
      AUTH_SERVICE_API_URL: ${{ secrets.AUTH_SERVICE_API_URL }}
      UNIVERSITY_SERVICE_INTERNAL_URL: ${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}
      UNIVERSITY_SERVICE_API_URL: ${{ secrets.UNIVERSITY_SERVICE_API_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          pip install -r requirements.txt
          docker compose up -d --build
          pytest --alluredir=allure-results
        continue-on-error: true

  allure-order:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@v4
      - name: Install Allure
        run: |
          wget -q https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip -q allure-2.27.0.zip -d $HOME/allure
          echo "$HOME/allure/allure-2.27.0/bin" >> $GITHUB_PATH
          export PATH="$HOME/allure/allure-2.27.0/bin:$PATH"
      - name: Generate Report
        run: mkdir -p allure-report
      - name: Publish Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: test
          force_orphan: true